language: ruby
bundler_args: --without=metrics
script: bundle exec rspec spec
sudo: false
gemfile:
  - gemfiles/activerecord-3.0
  - gemfiles/activerecord-4.0
  - gemfiles/activerecord-5.0
rvm:
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - jruby
  - rbx-2
matrix:
  exclude:
    - rvm: jruby
      gemfile: gemfiles/activerecord-5.0
    - rvm: rbx-2
      gemfile: gemfiles/activerecord-5.0
    - rvm: 2.5.0
      gemfile: gemfiles/activerecord-3.0
    - rvm: 2.6.0
      gemfile: gemfiles/activerecord-3.0
    - rvm: 2.7.0
      gemfile: gemfiles/activerecord-3.0
  allow_failures:
    - rvm: rbx-2
